Add unit tests for com.tagtraum.perf.gcviewer.math.DoubleData
Diffblue-benchmarks/Chewiebug-GCViewer pull request #1
Opened 2019-07-09 09:43 UTC by SimpsonAnna

I've analysed your codebase and noticed that `com.tagtraum.perf.gcviewer.math.DoubleData` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.

2019-07-09 09:45 UTC, JohnLBergqvist requested changes
I'm unsure whether you need to add in a 2nd `@Author` tag after line 11. What do you think @paulkennethkent ?

2019-07-09 09:45 UTC, JohnLBergqvist commented on src/test/java/com/tagtraum/perf/gcviewer/math/TestDoubleData.java
> +
You don't need a 2nd blank line here.

2019-07-09 09:50 UTC, SimpsonAnna commented on src/test/java/com/tagtraum/perf/gcviewer/math/TestDoubleData.java
> +
Resolved - thanks for the input John

2019-07-09 09:56 UTC, JohnLBergqvist approved these changes

2019-07-09 10:26 UTC, sudo-jaa approved these changes
Proud moment!

2019-07-09 10:49 UTC, paulkennethkent commented
> I'm unsure whether you need to add in a 2nd `@Author` tag after line 11. What do you think @paulkennethkent ?

Why not :) I would say @SimpsonAnna is a co-author of this file.

2019-07-10 10:56 UTC, paulkennethkent approved these changes

2020-01-23 09:52 UTC, merged